server.port=8080
spring.application.name=asba-print
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=30MB

spring.datasource.url=jdbc:sqlite:data/asba.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1
spring.sql.init.mode=always
